version: '3.8'

services:
  rx-veiculos:
    build: .
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=production
      - PORT=3000
      - NEXTAUTH_URL=http://31.97.92.120:3000
      - NEXTAUTH_SECRET=your-secret-key-here
      - NEXT_PUBLIC_SUPABASE_URL=your-supabase-url
      - NEXT_PUBLIC_SUPABASE_ANON_KEY=your-supabase-anon-key
      - SUPABASE_SERVICE_ROLE_KEY=your-supabase-service-role-key
      - DATABASE_URL=your-database-url
      - NEXT_PUBLIC_FIPE_API_TOKEN=your-fipe-token
      - NEXT_PUBLIC_APP_URL=http://31.97.92.120:3000
      - WEBSITE_URL=http://31.97.92.120:3000
    restart: unless-stopped
    healthcheck:
      test: ['CMD', 'wget', '-qO-', 'http://localhost:3000']
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s