# 🚗 RX Veículos - Docker Compose para Traefik
# Configuração para produção com Traefik reverse proxy e HTTPS automático

version: '3.8'

services:
  rx-veiculos:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=production
      - PORT=3000
      - NEXTAUTH_URL=https://rxnegocio.com.br
      - NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
      - NEXT_PUBLIC_SUPABASE_URL=${NEXT_PUBLIC_SUPABASE_URL}
      - NEXT_PUBLIC_SUPABASE_ANON_KEY=${NEXT_PUBLIC_SUPABASE_ANON_KEY}
      - SUPABASE_SERVICE_ROLE_KEY=${SUPABASE_SERVICE_ROLE_KEY}
      - DATABASE_URL=${DATABASE_URL}
      - WEBHOOK_URL=${WEBHOOK_URL}
      - ADMIN_EMAIL=${ADMIN_EMAIL}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_POOL_MODE=${POSTGRES_POOL_MODE}
      - NEXT_PUBLIC_FIPE_API_TOKEN=${NEXT_PUBLIC_FIPE_API_TOKEN}
      - NEXT_PUBLIC_APP_URL=https://rxnegocio.com.br
      - WEBSITE_URL=https://rxnegocio.com.br
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - traefik
    labels:
      # Habilitar Traefik
      - "traefik.enable=true"
      
      # Configuração da rede
      - "traefik.docker.network=traefik"
      
      # Configuração HTTP (redirecionamento para HTTPS)
      - "traefik.http.routers.rxveiculos-http.rule=Host(`rxnegocio.com.br`)"
      - "traefik.http.routers.rxveiculos-http.entrypoints=web"
      - "traefik.http.routers.rxveiculos-http.middlewares=redirect-to-https"
      
      # Configuração HTTPS
      - "traefik.http.routers.rxveiculos-https.rule=Host(`rxnegocio.com.br`)"
      - "traefik.http.routers.rxveiculos-https.entrypoints=websecure"
      - "traefik.http.routers.rxveiculos-https.tls=true"
      - "traefik.http.routers.rxveiculos-https.tls.certresolver=letsencrypt"
      
      # Configuração do serviço
      - "traefik.http.services.rxveiculos.loadbalancer.server.port=3000"
      
      # Middleware de redirecionamento HTTPS
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.permanent=true"

networks:
  traefik:
    external: true